name: Deploy to GitHub-Pages

on:
  workflow_dispatch:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build_and_deploy:
    permissions:
      contents: write
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: dart-lang/setup-dart@v1.3
      - uses: actions/checkout@v4
      - run: dart pub get
      - run: dart analyze --fatal-infos
      - run: dart format -onone --set-exit-if-changed $(git ls-files '*.dart')
      - run: dart run webdev build --release
      - uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          branch: gh-pages
          folder: build
